/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentConfigs: typeof import('./src/components/AgentConfigs.vue')['default']
    BAccordion: typeof import('bootstrap-vue-next/components/BAccordion')['BAccordion']
    BAccordionItem: typeof import('bootstrap-vue-next/components/BAccordion')['BAccordionItem']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    DisconnectedSteps: typeof import('./src/components/DisconnectedSteps.vue')['default']
    DnsEntries: typeof import('./src/components/DnsEntries.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InstallConfig: typeof import('./src/components/InstallConfig.vue')['default']
    InstallGuide: typeof import('./src/components/InstallGuide.vue')['default']
    Machines: typeof import('./src/components/Machines.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
