FROM registry.access.redhat.com/ubi9/nodejs-20:latest AS builder

USER 0

WORKDIR /opt/app-root/src

COPY . .

RUN npm install && npm run build


FROM registry.access.redhat.com/ubi9/nginx-124

USER 0
COPY --from=builder /opt/app-root/src/dist/ /tmp/src/
RUN chown -R 1001:0 /tmp/src
USER 1001

RUN /usr/libexec/s2i/assemble

CMD /usr/libexec/s2i/run